<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a3734bd6-247d-4ef6-903e-b4397c23b44d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\v1\Flights\AirlineTicket.Modules.Flights.Api\AirlineTicket.Modules.Flights.Api.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Bookings\AirlineTicket.Modules.Bookings.Api\AirlineTicket.Modules.Bookings.Api.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Users\AirlineTicket.Modules.Users.Api\AirlineTicket.Modules.Users.Api.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Flights\AirlineTicket.Modules.Flights.Application\AirlineTicket.Modules.Flights.Application.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Bookings\AirlineTicket.Modules.Bookings.Application\AirlineTicket.Modules.Bookings.Application.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Users\AirlineTicket.Modules.Users.Application\AirlineTicket.Modules.Users.Application.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Promotions\AirlineTicket.Modules.Promotions.Application\AirlineTicket.Modules.Promotions.Application.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Flights\AirlineTicket.Modules.Flights.Infrastructure\AirlineTicket.Modules.Flights.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Bookings\AirlineTicket.Modules.Bookings.Infrastructure\AirlineTicket.Modules.Bookings.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Users\AirlineTicket.Modules.Users.Infrastructure\AirlineTicket.Modules.Users.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Promotions\AirlineTicket.Modules.Promotions.Api\AirlineTicket.Modules.Promotions.Api.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Promotions\AirlineTicket.Modules.Promotions.Infrastructure\AirlineTicket.Modules.Promotions.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Interactions\AirlineTicket.Modules.Interactions.Api\AirlineTicket.Modules.Interactions.Api.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Interactions\AirlineTicket.Modules.Interactions.Application\AirlineTicket.Modules.Interactions.Application.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Interactions\AirlineTicket.Modules.Interactions.Infrastructure\AirlineTicket.Modules.Interactions.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\v1\CMS\AirlineTicket.Modules.CMS.Api\AirlineTicket.Modules.CMS.Api.csproj" />
    <ProjectReference Include="..\..\Modules\v1\CMS\AirlineTicket.Modules.CMS.Application\AirlineTicket.Modules.CMS.Application.csproj" />
    <ProjectReference Include="..\..\Modules\v1\CMS\AirlineTicket.Modules.CMS.Infrastructure\AirlineTicket.Modules.CMS.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Notifications\AirlineTicket.Modules.Notifications.Api\AirlineTicket.Modules.Notifications.Api.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Notifications\AirlineTicket.Modules.Notifications.Application\AirlineTicket.Modules.Notifications.Application.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Notifications\AirlineTicket.Modules.Notifications.Infrastructure\AirlineTicket.Modules.Notifications.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Logs\AirlineTicket.Modules.Logs.Api\AirlineTicket.Modules.Logs.Api.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Logs\AirlineTicket.Modules.Logs.Application\AirlineTicket.Modules.Logs.Application.csproj" />
    <ProjectReference Include="..\..\Modules\v1\Logs\AirlineTicket.Modules.Logs.Infrastructure\AirlineTicket.Modules.Logs.Infrastructure.csproj" />
  </ItemGroup>

</Project>
