version: '3.8'

services:
  airlineticket-api:
    image: airlineticket-backend:dev
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Chuỗi kết nối trỏ sang container SQL Server chạy cùng mạng nội bộ Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AirlineTicketDb;User Id=sa;Password=Admin@123;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    restart: always

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Admin@123
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data-dev:/var/opt/mssql
    restart: always

volumes:
  sqlserver-data-dev:
