<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\BuildingBlock\AirlineTicket.BuildingBlocks\AirlineTicket.BuildingBlocks.csproj" />
    <ProjectReference Include="..\AirlineTicket.Modules.Bookings.Domain\AirlineTicket.Modules.Bookings.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
