<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.5.3" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\appsettings.shared.json" Link="appsettings.shared.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\appsettings.shared.Development.json" Link="appsettings.shared.Development.json" Condition="Exists('..\..\appsettings.shared.Development.json')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Api\AirlineTicket.Api\AirlineTicket.Api.csproj" />
    <ProjectReference Include="..\..\Realtime\AirlineTicket.SignalR\AirlineTicket.SignalR.csproj" />
    <ProjectReference Include="..\..\Workers\AirlineTicket.Worker\AirlineTicket.Worker.csproj" />
  </ItemGroup>

</Project>
