// <auto-generated />
using System;
using AirlineTicket.Modules.Flights.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AirlineTicket.Modules.Flights.Infrastructure.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20260730021547_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flights")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.AircraftModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AircraftModels", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.AircraftModelSeatTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AircraftModelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsExtraLegroom")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PriceMultiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SeatClass")
                        .HasColumnType("integer");

                    b.Property<string>("SeatColumn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeatRow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AircraftModelId");

                    b.ToTable("AircraftModelSeatTemplates", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Airline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ApiEndpoint")
                        .HasColumnType("text");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<string>("BaseCountry")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupportEmail")
                        .HasColumnType("text");

                    b.Property<string>("SupportPhone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Airlines", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Airplane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AircraftModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AircraftModelId");

                    b.HasIndex("AirlineId");

                    b.ToTable("Airplanes", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.AirplaneSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AirplaneId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsExtraLegroom")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PriceMultiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SeatClass")
                        .HasColumnType("integer");

                    b.Property<string>("SeatColumn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeatRow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AirplaneId");

                    b.ToTable("AirplaneSeats", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Airport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CityEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CityVi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IataCode")
                        .IsUnique();

                    b.ToTable("Airports", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AirplaneId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AirplaneId");

                    b.HasIndex("RouteId");

                    b.ToTable("Flights", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.FlightSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExtraLegroom")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("PriceOverride")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SeatClass")
                        .HasColumnType("integer");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("FlightSeats", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DestinationAirportId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DistanceKm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OriginAirportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("OriginAirportId");

                    b.ToTable("Routes", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.AircraftModelSeatTemplate", b =>
                {
                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.AircraftModel", "AircraftModel")
                        .WithMany("SeatTemplates")
                        .HasForeignKey("AircraftModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AircraftModel");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Airplane", b =>
                {
                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.AircraftModel", "AircraftModel")
                        .WithMany("Airplanes")
                        .HasForeignKey("AircraftModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.Airline", "Airline")
                        .WithMany("Airplanes")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AircraftModel");

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.AirplaneSeat", b =>
                {
                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.Airplane", "Airplane")
                        .WithMany("AirplaneSeats")
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airplane");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Flight", b =>
                {
                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.Airplane", "Airplane")
                        .WithMany("Flights")
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.Route", "Route")
                        .WithMany("Flights")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airplane");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.FlightSeat", b =>
                {
                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.Flight", "Flight")
                        .WithMany("FlightSeats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Route", b =>
                {
                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.Airline", "Airline")
                        .WithMany("Routes")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.Airport", "DestinationAirport")
                        .WithMany("DestinationRoutes")
                        .HasForeignKey("DestinationAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.Airport", "OriginAirport")
                        .WithMany("OriginRoutes")
                        .HasForeignKey("OriginAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("DestinationAirport");

                    b.Navigation("OriginAirport");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.AircraftModel", b =>
                {
                    b.Navigation("Airplanes");

                    b.Navigation("SeatTemplates");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Airline", b =>
                {
                    b.Navigation("Airplanes");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Airplane", b =>
                {
                    b.Navigation("AirplaneSeats");

                    b.Navigation("Flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Airport", b =>
                {
                    b.Navigation("DestinationRoutes");

                    b.Navigation("OriginRoutes");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Flight", b =>
                {
                    b.Navigation("FlightSeats");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Route", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
