// <auto-generated />
using System;
using AirlineTicket.Modules.Flights.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AirlineTicket.Modules.Flights.Infrastructure.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20260805070046_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flights")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.AircraftModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer")
                        .HasColumnName("total_seats");

                    b.HasKey("Id")
                        .HasName("pk_aircraft_models");

                    b.ToTable("aircraft_models", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.AircraftModelSeatTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AircraftModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("aircraft_model_id");

                    b.Property<bool>("IsExtraLegroom")
                        .HasColumnType("boolean")
                        .HasColumnName("is_extra_legroom");

                    b.Property<decimal>("PriceMultiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_multiplier");

                    b.Property<int>("SeatClass")
                        .HasColumnType("integer")
                        .HasColumnName("seat_class");

                    b.Property<string>("SeatColumn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seat_column");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seat_number");

                    b.Property<string>("SeatRow")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seat_row");

                    b.HasKey("Id")
                        .HasName("pk_aircraft_model_seat_templates");

                    b.HasIndex("AircraftModelId")
                        .HasDatabaseName("ix_aircraft_model_seat_templates_aircraft_model_id");

                    b.ToTable("aircraft_model_seat_templates", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Airline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ApiEndpoint")
                        .HasColumnType("text")
                        .HasColumnName("api_endpoint");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text")
                        .HasColumnName("api_key");

                    b.Property<string>("BaseCountry")
                        .HasColumnType("text")
                        .HasColumnName("base_country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("iata_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SupportEmail")
                        .HasColumnType("text")
                        .HasColumnName("support_email");

                    b.Property<string>("SupportPhone")
                        .HasColumnType("text")
                        .HasColumnName("support_phone");

                    b.HasKey("Id")
                        .HasName("pk_airlines");

                    b.ToTable("airlines", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Airplane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AircraftModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("aircraft_model_id");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("uuid")
                        .HasColumnName("airline_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registration_number");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("total_capacity");

                    b.HasKey("Id")
                        .HasName("pk_airplanes");

                    b.HasIndex("AircraftModelId")
                        .HasDatabaseName("ix_airplanes_aircraft_model_id");

                    b.HasIndex("AirlineId")
                        .HasDatabaseName("ix_airplanes_airline_id");

                    b.ToTable("airplanes", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.AirplaneSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AirplaneId")
                        .HasColumnType("uuid")
                        .HasColumnName("airplane_id");

                    b.Property<bool>("IsExtraLegroom")
                        .HasColumnType("boolean")
                        .HasColumnName("is_extra_legroom");

                    b.Property<decimal>("PriceMultiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_multiplier");

                    b.Property<int>("SeatClass")
                        .HasColumnType("integer")
                        .HasColumnName("seat_class");

                    b.Property<string>("SeatColumn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seat_column");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seat_number");

                    b.Property<string>("SeatRow")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seat_row");

                    b.HasKey("Id")
                        .HasName("pk_airplane_seats");

                    b.HasIndex("AirplaneId")
                        .HasDatabaseName("ix_airplane_seats_airplane_id");

                    b.ToTable("airplane_seats", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Airport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CityEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city_en");

                    b.Property<string>("CityVi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city_vi");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("iata_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_vi");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("timezone");

                    b.HasKey("Id")
                        .HasName("pk_airports");

                    b.HasIndex("IataCode")
                        .IsUnique()
                        .HasDatabaseName("ix_airports_iata_code");

                    b.ToTable("airports", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AirplaneId")
                        .HasColumnType("uuid")
                        .HasColumnName("airplane_id");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrival_time");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_time");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flight_number");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_flights");

                    b.HasIndex("AirplaneId", "DepartureTime")
                        .HasDatabaseName("ix_flights_airplane_id_departure_time");

                    b.HasIndex("DepartureTime", "ArrivalTime")
                        .HasDatabaseName("ix_flights_departure_time_arrival_time");

                    b.HasIndex("RouteId", "DepartureTime")
                        .HasDatabaseName("ix_flights_route_id_departure_time");

                    b.ToTable("flights", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.FlightSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_id");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsExtraLegroom")
                        .HasColumnType("boolean")
                        .HasColumnName("is_extra_legroom");

                    b.Property<decimal?>("PriceOverride")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_override");

                    b.Property<int>("SeatClass")
                        .HasColumnType("integer")
                        .HasColumnName("seat_class");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seat_number");

                    b.HasKey("Id")
                        .HasName("pk_flight_seats");

                    b.HasIndex("FlightId", "IsAvailable")
                        .HasDatabaseName("ix_flight_seats_flight_id_is_available");

                    b.ToTable("flight_seats", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("uuid")
                        .HasColumnName("airline_id");

                    b.Property<Guid>("DestinationAirportId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_airport_id");

                    b.Property<decimal?>("DistanceKm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("distance_km");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("OriginAirportId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_airport_id");

                    b.HasKey("Id")
                        .HasName("pk_routes");

                    b.HasIndex("AirlineId")
                        .HasDatabaseName("ix_routes_airline_id");

                    b.HasIndex("DestinationAirportId")
                        .HasDatabaseName("ix_routes_destination_airport_id");

                    b.HasIndex("OriginAirportId")
                        .HasDatabaseName("ix_routes_origin_airport_id");

                    b.HasIndex("OriginAirportId", "DestinationAirportId")
                        .HasDatabaseName("ix_routes_origin_airport_id_destination_airport_id");

                    b.ToTable("routes", "flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.AircraftModelSeatTemplate", b =>
                {
                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.AircraftModel", "AircraftModel")
                        .WithMany("SeatTemplates")
                        .HasForeignKey("AircraftModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_aircraft_model_seat_templates_aircraft_models_aircraft_mode");

                    b.Navigation("AircraftModel");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Airplane", b =>
                {
                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.AircraftModel", "AircraftModel")
                        .WithMany("Airplanes")
                        .HasForeignKey("AircraftModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_airplanes_aircraft_models_aircraft_model_id");

                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.Airline", "Airline")
                        .WithMany("Airplanes")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_airplanes_airlines_airline_id");

                    b.Navigation("AircraftModel");

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.AirplaneSeat", b =>
                {
                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.Airplane", "Airplane")
                        .WithMany("AirplaneSeats")
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_airplane_seats_airplanes_airplane_id");

                    b.Navigation("Airplane");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Flight", b =>
                {
                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.Airplane", "Airplane")
                        .WithMany("Flights")
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_flights_airplanes_airplane_id");

                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.Route", "Route")
                        .WithMany("Flights")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_flights_routes_route_id");

                    b.Navigation("Airplane");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.FlightSeat", b =>
                {
                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.Flight", "Flight")
                        .WithMany("FlightSeats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_flight_seats_flights_flight_id");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Route", b =>
                {
                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.Airline", "Airline")
                        .WithMany("Routes")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_routes_airlines_airline_id");

                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.Airport", "DestinationAirport")
                        .WithMany("DestinationRoutes")
                        .HasForeignKey("DestinationAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_routes_airports_destination_airport_id");

                    b.HasOne("AirlineTicket.Modules.Flights.Domain.Entities.Airport", "OriginAirport")
                        .WithMany("OriginRoutes")
                        .HasForeignKey("OriginAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_routes_airports_origin_airport_id");

                    b.Navigation("Airline");

                    b.Navigation("DestinationAirport");

                    b.Navigation("OriginAirport");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.AircraftModel", b =>
                {
                    b.Navigation("Airplanes");

                    b.Navigation("SeatTemplates");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Airline", b =>
                {
                    b.Navigation("Airplanes");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Airplane", b =>
                {
                    b.Navigation("AirplaneSeats");

                    b.Navigation("Flights");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Airport", b =>
                {
                    b.Navigation("DestinationRoutes");

                    b.Navigation("OriginRoutes");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Flight", b =>
                {
                    b.Navigation("FlightSeats");
                });

            modelBuilder.Entity("AirlineTicket.Modules.Flights.Domain.Entities.Route", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
